### ISSUE TITLE
Docker Compose Sass Error

### ISSUE THREAD

**Issue by HaruVON** [rishighan/threetwo#101]
Upon following the docker-compose unraid tutorial I'm getting the following error on the UI:
`[vite:css] Preprocessor dependency "sass" not found. Did you install it? Try npm install -D sass.`

**Comment by EkielZan** [comment]
Got the same issues : 


`✓ built in 1.80s
[vite:css] Preprocessor dependency "sass" not found. Did you install it? Try `npm install -D sass`.
file: /threetwo/src/client/assets/scss/App.scss
error during build:
Error: Preprocessor dependency "sass" not found. Did you install it? Try `npm install -D sass`.
    at loadPreprocessor (file:///threetwo/node_modules/vite/dist/node/chunks/dep-df561101.js:39269:19)
    at scss (file:///threetwo/node_modules/vite/dist/node/chunks/dep-df561101.js:39310:20)
    at compileCSSPreprocessors (file:///threetwo/node_modules/vite/dist/node/chunks/dep-df561101.js:38735:36)
    at compileCSS (file:///threetwo/node_modules/vite/dist/node/chunks/dep-df561101.js:38785:42)
    at async Object.transform (file:///threetwo/node_modules/vite/dist/node/chunks/dep-df561101.js:38266:56)
    at async transform (file:///threetwo/node_modules/rollup/dist/es/shared/node-entry.js:24367:16)
    at async ModuleLoader.addModuleSource (file:///threetwo/node_modules/rollup/dist/es/shared/node-entry.js:24567:30)`

**Comment by francop311** [comment]
Any update on this?

I am getting the same issue.

Perhaps a quick fix is to update the Dockerfile to include sass during install?

**Comment by rishighan** [comment]
I'll get to updating the individual images this weekend. I'm busy currently with automating download functionality, once that is complete, I can fix this.

**Comment by francop311** [comment]
Other issue is with the core-services container where it complains about incorrect version of node.js.

Below is part of the error log:

```
[2024-05-06T15:49:26.121Z] ERROR threetwo-core-service/BROKER: Failed to load service '/core-services/dist/services/imagetransformation.service.js' Error: Could not load the "sharp" module using the linuxmusl-x64 runtime
Possible solutions:
- Please upgrade Node.js:
    Found 14.21.3
    Requires ^18.17.0 || ^20.3.0 || >=21.0.0
```

**Comment by rishighan** [comment]
The latest update to https://github.com/rishighan/threetwo-docker-compose should fix this. Closing this issue, feel free to re-open if it persists.

**Comment by SleepingPanda** [comment]
These issues still exist. I'm not sure what's the correct procedure with setting up threetwo. The unraid guide seems to be out of date and the docker-compose file on github is missing lots of details. There are numerous questions asking for help with both of these issues but @rishighan never addresses them. This issue is still present.

**Comment by rishighan** [comment]
I'd love to have the time to sort `docker-compose` out. I just don't right now. I'm focused on DC++ automation. I've repeatedly stated that any sort of insight into this issue is appreciated, while I sort the more pressing issues out. I'd love for this forum to be the one for productive conversation. 

Like thousands of other authors of open source software, I try to do the best I can with what I have. Sometimes that means I deprioritize issues in favor of more pressing ones.

**Comment by SleepingPanda** [comment]
In that case, since its a fact docker isn't working right now, maybe consider removing the instructions or adding a warning they're not working since they only lead to circular discussion that goes nowhere.
